name: UI visual testing

on:
  push:
    branches:
      - main-disabled # disable for now
    paths-ignore:
    - 'bigquery/**'
    - 'documentation/**'
    - 'terraform/common/**'
    - 'terraform/monitoring/**'
    - '**.md'

  # pull_request:
  #   branches:
  #     - main

jobs:

  frontend-tests:
    name: Run backstop

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup frontend visual regression
        run: |
          PR_ID=${{ github.event.number }}
          echo "PR_ID=${PR_ID}" >> $GITHUB_ENV

      - name: run frontend visual regression
        run: |
          yarn install
          yarn run visual:test:jobseeker
